<div class="col-md-3 padding-left"><div class="postIt">
    <ul class="list-group">
        <li class="list-group-item">
            <img src="images/icons/index.gif" alt="index termeni tehnici" title=" index termeni tehnici " width="18" height="22">            <a target="_blank" href="{{$siteurl}}/pdf/Dictionar-Tehnic-Englez-Roman.pdf">Index termeni tehnici</a>
        </li>
        <li class="list-group-item">
            <img src="images/icons/convertor.gif" alt="calculator unitati de masura" title=" calculator unitati de masura " width="18" height="22">            <a href="{{$siteurl}}/convertor.php">Convertor unitati de masura</a>
        </li>
    </ul>
</div>

<article class="nicePromoBox"><h3><a href="{{$siteurl}}/best_sellers.php">Cele mai vandute</a></h3><a href="{{$siteurl}}/panza-rectilinie-hss-500-mm-pilana-p-6073.html" title="Panza rectilinie HSS 500 mm PILANA"><img src="images/mari/3/3502516006.jpg" alt="Panza rectilinie HSS 500 mm PILANA" title=" Panza rectilinie HSS 500 mm PILANA " width="130" height="130"></a><p><a href="{{$siteurl}}/panza-rectilinie-hss-500-mm-pilana-p-6073.html">Panza rectilinie HSS 500 mm PILANA</a></p><div class="col-sm-6"><span class="pNew">76,15 Lei</span></div><div class="col-sm-6"><a class="buyNow" href="{{$siteurl}}/index.php?action=buy_now&amp;products_id=6073">Adauga in cos</a></div></article><article class="nicePromoBox"><h3><a href="{{$siteurl}}/specials.php">Promotii</a></h3><a href="{{$siteurl}}/cheie-fixa-simpla-brunata-1174-unior-p-9.html" title="Cheie fixa simpla brunata 117/4 UNIOR"><img src="images/mari/6/615262.jpg" alt="Cheie fixa simpla brunata 117/4 UNIOR" title=" Cheie fixa simpla brunata 117/4 UNIOR " width="130" height="130"></a><p><a href="{{$siteurl}}/cheie-fixa-simpla-brunata-1174-unior-p-9.html">Cheie fixa simpla brunata 117/4 UNIOR</a></p><div class="col-sm-6"><span class="pOld">6,67 Lei</span><span class="pNew">5,84 Lei</span></div><div class="col-sm-6"><a class="buyNow" href="{{$siteurl}}/index.php?action=buy_now&amp;products_id=9">Adauga in cos</a></div></article><article class="nicePromoBox"><h3><a href="{{$siteurl}}/new_products.php">Produse noi</a></h3><a href="{{$siteurl}}/polizor-de-banc-600-discuri-200-mm-gbg-bosch-p-26180.html" title="Polizor de banc 600 W discuri 200 mm GBG 8 BOSCH"><img src="images/mari/0/060127A100.jpg" alt="Polizor de banc 600 W discuri 200 mm GBG 8 BOSCH" title=" Polizor de banc 600 W discuri 200 mm GBG 8 BOSCH " width="130" height="130"></a><p><a href="{{$siteurl}}/polizor-de-banc-600-discuri-200-mm-gbg-bosch-p-26180.html">Polizor de banc 600 W discuri 200 mm GBG 8 BOSCH</a></p><div class="col-sm-6"><span class="pNew">1.098,00 Lei</span></div><div class="col-sm-6"><a class="buyNow" href="{{$siteurl}}/index.php?action=buy_now&amp;products_id=26180">Adauga in cos</a></div></article></div>
